name: proyecto_dogzline
description: "A new Flutter project focused on DogzLine."
publish_to: 'none' # Indica que el proyecto no se publicará en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Compatibilidad con Flutter SDK estable

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0 # Asegúrate de que ya tienes Dio
  shared_preferences: ^2.0.0
  jwt_decoder: ^2.0.1
  flutter_image_compress: ^2.4.0 # Asegúrate de usar la última versión
  cupertino_icons: ^1.0.8 # Iconos estilo Cupertino para compatibilidad con iOS
  font_awesome_flutter: ^10.1.0 # Iconos FontAwesome para Flutter
  image_picker: ^0.8.4+3 # Paquete para seleccionar imágenes
  swipe_cards: ^2.0.0+1 # Paquete para la funcionalidad de swipe
  google_fonts: ^4.0.0 # Paquete para usar Google Fonts en Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Buenas prácticas y recomendaciones de linting

flutter:
  uses-material-design: true # Habilita el uso de Material Icons

  # Ruta para los recursos gráficos (imágenes, logos, etc.)
  assets:
    - assets/Logo_dogzline.png # Cambia esta ruta si tu imagen tiene otro nombre o ubicación

  # Configuración opcional para fuentes personalizadas
  # fonts:
  #   - family: NombreFuente
  #     fonts:
  #       - asset: assets/fonts/NombreFuente-Regular.ttf
  #       - asset: assets/fonts/NombreFuente-Bold.ttf
  #         weight: 700